### ISSUE TITLE
TypeError: Cannot destructure property `env` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by jcowman2** [pmowrer/semantic-release-github-pr#33] opened 2018-09-06 05:09 UTC
Hello, I am having trouble running your plugin.

When I run `npx semantic-release-github-pr`, I get the following error:

```
[23:54:36] [semantic-release] » i  Running semantic-release version 15.9.12
[23:54:36] [semantic-release] » √  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[23:54:36] [semantic-release] » √  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[23:54:37] [semantic-release] » √  Loaded plugin "verifyConditions" from "@semantic-release/git"
[23:54:37] [semantic-release] » √  Loaded plugin "analyzeCommits" from "C:\Users\Joe\Documents\GitHub\test-release-workflow\node_modules\semantic-release-github-pr\src\index.js"
[23:54:37] [semantic-release] » √  Loaded plugin "generateNotes" from "C:\Users\Joe\Documents\GitHub\test-release-workflow\node_modules\semantic-release-github-pr\src\index.js"
[23:54:37] [semantic-release] » √  Loaded plugin "prepare" from "@semantic-release/changelog"
[23:54:37] [semantic-release] » √  Loaded plugin "prepare" from "@semantic-release/npm"
[23:54:37] [semantic-release] » √  Loaded plugin "prepare" from "@semantic-release/git"
[23:54:37] [semantic-release] » √  Loaded plugin "publish" from "@semantic-release/npm"
[23:54:37] [semantic-release] » √  Loaded plugin "publish" from "@semantic-release/github" in shareable config "C:\Users\Joe\Documents\GitHub\test-release-workflow\node_modules\semantic-release-github-pr\src\index.js"
[23:54:37] [semantic-release] » √  Loaded plugin "success" from "@semantic-release/github" in shareable config "C:\Users\Joe\Documents\GitHub\test-release-workflow\node_modules\semantic-release-github-pr\src\index.js"
[23:54:37] [semantic-release] » √  Loaded plugin "fail" from "@semantic-release/github" in shareable config "C:\Users\Joe\Documents\GitHub\test-release-workflow\node_modules\semantic-release-github-pr\src\index.js"
[23:54:37] [semantic-release] » √  Run automated release from branch change-foo
[23:54:40] [semantic-release] » √  Allowed to push to the Git repository
[23:54:40] [semantic-release] » i  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[23:54:40] [semantic-release] » √  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[23:54:40] [semantic-release] » i  Start step "verifyConditions" of plugin "@semantic-release/npm"
[23:54:40] [semantic-release] [@semantic-release/npm] » i  Verify authentication for registry https://registry.npmjs.org/
[23:54:41] [semantic-release] » √  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[23:54:41] [semantic-release] » i  Start step "verifyConditions" of plugin "@semantic-release/git"
[23:54:41] [semantic-release] » √  Completed step "verifyConditions" of plugin "@semantic-release/git"
[23:54:43] [semantic-release] » i  Found git tag v2.1.0 associated with version 2.1.0
[23:54:43] [semantic-release] » i  Found 5 commits since last release
[23:54:43] [semantic-release] » i  Start step "analyzeCommits" of plugin "C:\Users\Joe\Documents\GitHub\test-release-workflow\node_modules\semantic-release-github-pr\src\index.js"
[23:54:43] [semantic-release] » ×  Failed step "analyzeCommits" of plugin "C:\Users\Joe\Documents\GitHub\test-release-workflow\node_modules\semantic-release-github-pr\src\index.js"
[23:54:43] [semantic-release] » ×  An error occurred while running semantic-release: { TypeError: Cannot destructure property `env` of 'undefined' or 'null'.
    at module.exports (C:\Users\Joe\Documents\GitHub\test-release-workflow\node_modules\@semantic-release\github\lib\resolve-config.js:4:99)
    at module.exports.pluginConfig (C:\Users\Joe\Documents\GitHub\test-release-workflow\node_modules\semantic-release-github-pr\src\github-init.js:12:59)
    at C:\Users\Joe\Documents\GitHub\test-release-workflow\node_modules\semantic-release-github-pr\src\with-github.js:6:18
    at validator (C:\Users\Joe\Documents\GitHub\test-release-workflow\node_modules\semantic-release\lib\plugins\normalize.js:34:28)
    at pReduce (C:\Users\Joe\Documents\GitHub\test-release-workflow\node_modules\semantic-release\lib\plugins\pipeline.js:37:40)
    at Promise.all.then.value (C:\Users\Joe\Documents\GitHub\test-release-workflow\node_modules\p-reduce\index.js:16:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  pluginName: 'C:\\Users\\Joe\\Documents\\GitHub\\test-release-workflow\\node_modules\\semantic-release-github-pr\\src\\index.js' }
{ TypeError: Cannot destructure property `env` of 'undefined' or 'null'.
    at module.exports (C:\Users\Joe\Documents\GitHub\test-release-workflow\node_modules\@semantic-release\github\lib\resolve-config.js:4:99)
    at module.exports.pluginConfig (C:\Users\Joe\Documents\GitHub\test-release-workflow\node_modules\semantic-release-github-pr\src\github-init.js:12:59)
    at C:\Users\Joe\Documents\GitHub\test-release-workflow\node_modules\semantic-release-github-pr\src\with-github.js:6:18
    at validator (C:\Users\Joe\Documents\GitHub\test-release-workflow\node_modules\semantic-release\lib\plugins\normalize.js:34:28)
    at pReduce (C:\Users\Joe\Documents\GitHub\test-release-workflow\node_modules\semantic-release\lib\plugins\pipeline.js:37:40)
    at Promise.all.then.value (C:\Users\Joe\Documents\GitHub\test-release-workflow\node_modules\p-reduce\index.js:16:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  pluginName: 'C:\\Users\\Joe\\Documents\\GitHub\\test-release-workflow\\node_modules\\semantic-release-github-pr\\src\\index.js' }
```
Note that `npx semantic-release` works fine for me.

**Comment by pmowrer** [comment] 2018-09-06 20:26
Thanks for the report @jcowman2! This looks like a duplicate of https://github.com/Updater/semantic-release-github-pr/issues/28. I'm working on a fix for this so hang tight!

**Closed as completed by pmowrer** 2018-09-06 20:26 UTC
